### ISSUE TITLE
Please Explain following terms while requesting perfcollector.js 

### ISSUE THREAD

**Issue by Ashesh007** [Fovea/perfcollector.js#2]
Total Time, avg time and max time while requesting perfcollector.js following output is shown.
PFA

![screenshot from 2015-01-19 12 27 40](https://cloud.githubusercontent.com/assets/6592432/5796931/fda5f10e-9fd6-11e4-9356-5eacdaaaecaf.png)

**Comment by j3k0** [comment]
- `1 calls` i.e. filter_details has been called 1 time.
- `total: 2ms` i.e. it took a total of 2ms of the application running time.
- `avg: 2ms` i.e. each call took on average 2ms.
- `max: 2ms` i.e. in the worst case, it took 2ms.

I hope this is clear! Let me know.

**Comment by Ashesh007** [comment]
thnks

**Comment by Ashesh007** [comment]
how to find which function are called and how much time is taken by each function??

**Comment by j3k0** [comment]
You have to instrument yourself what you want to measure.
